In [227]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing The Dataset

In [228]:
df1 = pd.read_csv("Position_Salaries.csv")

In [229]:
df1.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [230]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Position  10 non-null     object
 1   Level     10 non-null     int64 
 2   Salary    10 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


# Appling Label Encoder On "Position" Column

In [231]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df1["Position"] = le.fit_transform(df1["Position"])

In [232]:
df1.head()

Position  Level  Salary
0         0      1   45000
1         4      2   50000
2         8      3   60000
3         5      4   80000
4         3      5  110000

# Data Splitting

In [233]:
X = df1.iloc[ : , 0:2].values
y = df1.iloc[ : , -1].values.reshape(10,1)

In [234]:
X

array([[ 0,  1],
       [ 4,  2],
       [ 8,  3],
       [ 5,  4],
       [ 3,  5],
       [ 7,  6],
       [ 6,  7],
       [ 9,  8],
       [ 1,  9],
       [ 2, 10]], dtype=int64)

In [235]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]], dtype=int64)

# Train and Test Splitting

In [236]:
from sklearn.model_selection import train_test_split

Xtrain , Xtest , ytrain , ytest = train_test_split( X, y, test_size=0.5, random_state=0)

# Decision Tree Classifier Algorithm

In [237]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

model_DTC = DecisionTreeClassifier(max_depth= 3, random_state=0)
model_DTC.fit(Xtrain, ytrain)
ypred_DTC = model_DTC.predict(Xtest)
model_DTC.predict([[5,  4]])

acc_DTC = model_DTC.score(Xtest,ytest)
accscore_DTC = accuracy_score(ytest, ypred_DTC)
print(f"Accuracy Of Decision Tree Classifier : {acc_DTC*100:.2f}%")
print(f"Accuracy Of Decision Tree Classifier : {accscore_DTC*100:.2f}%")

Accuracy Of Decision Tree Classifier : 0.00%
Accuracy Of Decision Tree Classifier : 0.00%


### I don't Know How The Accuracy is 0.0%, But It Seems That There Is Something Wrong

# Random Forest Classifier Algorithm

In [238]:
from sklearn.ensemble import RandomForestClassifier


model_RFC = RandomForestClassifier(n_estimators=20, random_state=0)
model_RFC.fit(Xtrain, ytrain)
ypred_RFC = model_RFC.predict(Xtest)
model_RFC.predict([[5,  4]])

acc_RFC = model_RFC.score(Xtest, ytest)
accscore_RFC = accuracy_score(ytest, ypred_RFC)
print(f"Accuracy Of Random Forest Classifier : {acc_RFC*100:.2f}%")
print(f"Accuracy Of Random Forest Classifier : {accscore_RFC*100:.2f}%")

Accuracy Of Random Forest Classifier : 0.00%
Accuracy Of Random Forest Classifier : 0.00%


C:\Users\Alaswad\AppData\Local\Temp\ipykernel_17884\2115727558.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model_RFC.fit(Xtrain, ytrain)


### I don't Know How The Accuracy is 0.0%, But It Seems That There Is Something Wrong

#############################################################################################################

# Importing The Dataset

In [239]:
df2 = pd.read_csv("Social_Network_Ads (1).csv")

In [240]:
df2.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [241]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


# Appling Label Encoder On "Gender" Column

In [242]:
le = LabelEncoder()
df2["Gender"]=le.fit_transform(df2["Gender"])

In [243]:
df2.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [244]:
X = df2.iloc[ : , 1:4].values
y = df2.iloc[ : , -1].values

In [245]:
X

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]], dtype=int64)

In [246]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [247]:
Xtrain , Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3,random_state=0)

# Decision Tree Classifier Algorithm

In [248]:
model_DTC = DecisionTreeClassifier(max_depth=4, random_state=0)
model_DTC.fit(Xtrain, ytrain)
ypred_DTC = model_DTC.predict(Xtest)

acc_DTC = model_DTC.score(Xtest,ytest)
accscore_DTC = accuracy_score(ytest, ypred_DTC)
print(f"Accuracy Of Decision Tree Classifier : {acc_DTC*100:.2f}%")
print(f"Accuracy Of Decision Tree Classifier : {accscore_DTC*100:.2f}%")

Accuracy Of Decision Tree Classifier : 90.83%
Accuracy Of Decision Tree Classifier : 90.83%


### Accuracy is Good 

# Random Forest Classifier Algorithm

In [249]:
model_RFC = RandomForestClassifier(n_estimators=20, random_state=0)
model_RFC.fit(Xtrain, ytrain)
ypred_RFC = model_RFC.predict(Xtest)

acc_RFC = model_RFC.score(Xtest, ytest)
accscore_RFC = accuracy_score(ytest, ypred_RFC)
print(f"Accuracy Of Random Forest Classifier : {acc_RFC*100:.2f}%")
print(f"Accuracy Of Random Forest Classifier : {accscore_RFC*100:.2f}%")

Accuracy Of Random Forest Classifier : 91.67%
Accuracy Of Random Forest Classifier : 91.67%


### Accuracy is Better Than The Decision Tree Classifier